spring:
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
  rabbitmq:
    password: guest
    port: '5672'
    host: localhost
    listener:
      simple:
        exclusive: 'false'
    username: guest
  config:
    import: optional:configserver:http://localhost:8012
  application:
    name: project1
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
server:
  port: '0'
