spring:
  application:
    name: discoveryservice
eureka:
  server:
    eviction-interval-timer-in-ms: 1000   # Run cleanup every 5 seconds
    enable-self-preservation: true       # Disable self-preservation (forces cleanup)
    renewal-percent-threshold: 0.85
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8761

