spring:
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      listener:
        simple:
          exclusive: false

  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: [classpath:/proj]
  application:
    name: config-server

server:
  port: 8012
#  http://localhost:8012/proj/default - default config endpoint

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
